version: 1.8

# any config here can be overwriteen by code

# data
site: jpl_ev
filename: data/all_JPL_v5.csv
index_col: Datetime
target_col: Load
feature_cols: ['Persist1Workday'] # includes target_col (list or empty)
benchmark_col: # if empty need to define benchmark_persist_days
benchmark_persist_days: 1  # calculate benchmark by persisting target_col by this many days
remove_days: weekends
resample: 15min

# model
results_dir: ./results/
clean_dir: False
units_layers: [1,0]
dropout: [0,0]
input_length: 1 # days
output_length: 1 # days
batch_size: 256
features: #[Persist1Workday] # list or empty
imf_features: [3,4]
calendar_features: False

# train
epochs: 1
patience: 10
plots: #'hx'
verbose: 1
valid_split: 0.2
loss: mse

# test
test_split: 0.1
forecast_freq: 1d # 1h or 1d
test_plots: False
test_output: True

# hyperparam search
search: True
continue_search: False
units1: [4,8,12,24,48,96,128,256,512,1024]
units2: [0,4,8,12,24,48,96,128,256,512,1024]
dropouts: [0,0.1]
input_lengths: [0.25,0.5,0.75,1,2,3,7,14] # days
features_2D: [ ['Persist1Workday'],
            ['Persist1Workday','IMF3',IMF4] ]

# viz
plot_style: 'seaborn-v0_8' # (empty), 'darkbackground', 'ggplot', 'fivethirtyeight', 'seaborn-v0_8'
