version: 1.6

# any configs here can be overwriteen by code

# data
# pers1D nMAEall=10.6%, nMSEall=0.0492, nMSEtrn=0.0478, nMSEvld=0.0526, nMSEtst=0.0512
# pers7D nMAEall=6.0%, nMSEall=0.0229, nMSEtrn=0.0228, nMSEvld=0.0247, nMSEtst=0.0200
# pers1WD nMAEall=5.1%, nMSEall=0.0159, nMSEtrn=0.0158, nMSEvld=0.0173, nMSEtst=0.0136

site: jpl_ev_TEST
filename: data/all_JPL_v5.csv
index_col: Datetime
data_col: Load
persist_col: #Persist
persist_calc_days: 7 # int or False (then need a persist_col above)
remove_days: weekends
resample: 15min
test_split: 0.05
emd: True
results_dir: ./results/
clean_dir: False

# model
units_layers: [12,96]
dropout: [0.1,0.1]
n_in: 96
n_out: 96
batch_size: 256
features: [Load, Persist1Workday]
features_list_name: IMF
#features_list_numbers: []
features_list_numbers: [3,4]
calendar_features: False

# training
epochs: 100
patience: 10
plots: #'hx'
verbose: 1
valid_split: 0.2
loss: mse

# testing
forecast_freq: 1d # 1h or 1d
test_plots: False
test_output: False

# search
search: False
units1: [4,8,12,24,48,96,128,256] # units 1
units2: [0,4,8,12,24,48,96,128,256] # units 2
dropouts: [0, 0.1] #0,0.1] # dropout
ns: [12,24,48,96,192,288,384,480] # n_in
features_2D: [  ['Load'], # features
                ['Load','Persist1Workday'], # features
                ['Load','IMF3','IMF4'],
                ['Load','Persist1Workday','IMF3','IMF4'],
                #['Load','IMF1','IMF2','IMF3','IMF4','IMF5','IMF6','IMF7','IMF8','IMF9','IMF10'],
                #['Load','Persist1Workday','IMF1','IMF2','IMF3','IMF4','IMF5','IMF6','IMF7','IMF8','IMF9','IMF10'],
                ]