version: 1.6

# any configs here can be overwriteen by code

# data
# pers1D nMAE all = 10.6%
# pers7D nMAE all = 6.0%
# pers1WD nMAE all = 5.1%
site: jpl_ev_241024
filename: data/all_JPL_v5.csv
index_col: Datetime
data_col: Load
persist_col: #Persist
persist_calc_days: 7 # int or False (then need a persist_col above)
remove_days: weekends
resample: 15min
test_split: 0.1
emd: True

# model
results_dir: ./results/
clean_dir: False
units_layers: [256,256]
dropout: [0,0]
n_in: 96
n_out: 96
batch_size: 256
features: [Load, Persist1Workday]
features_list_name: IMF
#features_list_numbers: []
features_list_numbers: [3,4]
calendar_features: False

# training
epochs: 300
patience: 10
plots: #'hx'
verbose: 1
valid_split: 0.2
loss: mse

# testing
forecast_freq: 1d # 1h or 1d
test_plots: False
test_output: False

# search
search: True
units1: [4,8,12,24,48,96,128,256] # units 1
units2: [0,4,8,12,24,48,96,128,256] # units 2
dropouts: [0, 0.1] #0,0.1] # dropout
ns: [12,24,48,96,192,288,384,480] # n_in
features_2D: [  ['Load'], # features
                ['Load','Persist1Workday'], # features
                ['Load','IMF3','IMF4'],
                ['Load','Persist1Workday','IMF3','IMF4'],
                #['Load','IMF1','IMF2','IMF3','IMF4','IMF5','IMF6','IMF7','IMF8','IMF9','IMF10'],
                #['Load','Persist1Workday','IMF1','IMF2','IMF3','IMF4','IMF5','IMF6','IMF7','IMF8','IMF9','IMF10'],
                ]